### ISSUE TITLE
running compiled app with node

### ISSUE THREAD

**Issue by bowenisdum** [janoist1/universal-react-redux-starter-kit#7]
@janoist1 sorry not really an issue, I think, but trying to figure out how to boot up the pre compiled app by doing:

 `npm run deploy:prod`

followed by 

`node dist/server.js` 

nothing happens the command returns with no errors, and no server is booted up, any hint whats the proper way to do this?

**Comment by bowenisdum** [comment]
Some more input:

I tried this fllow:

```
npm install --production
npm run deploy:prod
npm run start:prod
```

I get the following error:

```
Error: Cannot find module 'webpack-dev-middleware'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (webpack-dev.js:1:1)
    at Module._compile (module.js:541:32)
    at loader (/Users/bli/Projects/universal-react-redux-starter-kit/node_modules/babel-register/lib/node.js:148:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/bli/Projects/universal-react-redux-starter-kit/node_modules/babel-register/lib/node.js:158:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

Update:

seems to have worked after adding  follow deps to the regular depdencies listing, which is pretty weird, they shouldn't be required for prod

```
+    "webpack-dev-middleware": "^1.6.1",
+    "webpack-hot-middleware": "^2.6.0"
```

**Comment by janoist1** [comment]
@bowenisdum, there is an npm command `npm run start:prod` - have you tried that?

**Comment by bowenisdum** [comment]
yep, sorry totally our problem :)

**Comment by tylercrosse** [comment]
The original issue seems to still be valid. Why bother building `./dist/server.js` if the entry to the production app is `./bin/server.js`?
